### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by dungquoctrinh** [TinkersStudio/SeniorProjectDocument#2]
Write the project proposal

**Comment by dungquoctrinh** [comment]
@nqta0611 Please write the part about clone the repo.(marked as TODO in the document). It is the practice on git and the editing. Tag me in when you completed that part

The project proposal can be waited later if needed

**Comment by nqta0611** [comment]
@dungquoctrinh Done writing Clone the Repo

**Comment by dungquoctrinh** [comment]
@nqta0611 Task is completed done!!
